---
- name: detect that ethernet connection exists
  shell: "ip link show {{ eth_connection }}"
  changed_when: false
  register: eth_connection_found
  failed_when:
    - fail_for_missing_eth_connection
    - eth_connection_found.rc != 0

- name: create the bridge
  include_tasks: createbridge.yml
  when: eth_connection_found is succeeded
